version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3008:3008
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:mysecretpassword@localhost:5433do/mydb?schema=public
      - JWT_SECRET=5eb115783777b2f872f0a412e8419685
      - PORT=3008
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=admin
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
